sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sebtalbot/tuto_multi_docker_deploy_test_react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sebtalbot/tuto_multi_docker_deploy_test_react npm run test -- --coverage

after_success:
  - docker build -t sebtalbot/tuto_multi_docker_deploy_client ./client
  - docker build -t sebtalbot/tuto_multi_docker_deploy_server ./server
  - docker build -t sebtalbot/tuto_multi_docker_deploy_worker ./worker
  - docker build -t sebtalbot/tuto_multi_docker_deploy_nginx ./nginx
